colombates_reports/capa_web/Controllers/ReporteController.cs
using capa_logica_negocio.Maestras;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace capa_web.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            return View("~/Views/Shared/NoHayNadaAqui");
        }

        [HttpPost]
        public JsonResult ObtenerNombresReportes()
        {
            return Json(ReporteModel.ObtenerReportes());
        }

        public ActionResult HorasExtraMes()
        {
            return View();
        }

        public ActionResult HorasExtraPlantaAcumulada()
        {
            return View();
        }

        public ActionResult HorasHombrePlantaSacos()
        {
            return View();
        }

        public ViewResult General()
        {
            return View();
        }
    }
}

colombates_reports/capa_web/Views/Shared/NoHayNadaAqui.cshtml
@{
    ViewBag.Title = "No hay nada aquí";
}

<hgroup>
    <h1 class="text-danger">No hay nada aquí :(</h1>
    <h2 class="text-danger">Parece que no hemos encontrado lo que buscas.</h2>
</hgroup>

colombates_reports/capa_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Colombates Reports</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css?v=" + DateTime.Now.Ticks.ToString())
    @Styles.Render("~/Content/kendo/kendo.default.min.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_navbar")
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Colombates Reports</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/kendo")
    @Scripts.Render("~/Scripts/bootbox.min.js")
    @Scripts.Render("~/Scripts/general.js?v=" + DateTime.Now.Ticks.ToString())
    <script>kendo.culture("es-CO");</script>

    @RenderSection("scripts", required: false)
</body>
</html>

colombates_reports/capa_web/Views/Shared/_navbar.cshtml
@using Microsoft.AspNet.Identity
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Colombates Reports", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>

                @if (Request.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">General <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Centro" ? "active" : "")">
                                @Html.ActionLink("Centros", "Index", "Centro")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Objetivo" ? "active" : "")">
                                @Html.ActionLink("Objetivos", "Index", "Objetivo")
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Horas Hombre <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Turno" ? "active" : "")">
                                @Html.ActionLink("Turnos", "Index", "Turno")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "TipoHora" ? "active" : "")">
                                @Html.ActionLink("Tipos de Hora", "Index", "TipoHora")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "GrupoCausalExtra" ? "active" : "")">
                                @Html.ActionLink("Grupos Causales de Extra", "Index", "GrupoCausalExtra")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "CausalExtra" ? "active" : "")">
                                @Html.ActionLink("Causales de Extra", "Index", "CausalExtra")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Empleado" ? "active" : "")">
                                @Html.ActionLink("Empleados", "Index", "Empleado")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "HorasProgramadasMes" ? "active" : "")">
                                @Html.ActionLink("Horas Programadas por Mes", "Index", "HorasProgramadasMes")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "EmpleadoSemana" ? "active" : "")">
                                @Html.ActionLink("Cantidad Empleados Semanal", "Index", "EmpleadoSemana")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "CorteNominaPlanta" ? "active" : "")">
                                @Html.ActionLink("Corte Nomina Planta", "Index", "CorteNominaPlanta")
                            </li>
                            <li role="separator" class="divider"></li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "NovedadEmpleado" ? "active" : "")">
                                @Html.ActionLink("Novedades", "Index", "NovedadEmpleado")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Extra" ? "active" : "")">
                                @Html.ActionLink("Extras", "Index", "Extra")
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Productividad <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Proceso" ? "active" : "")">
                                @Html.ActionLink("Procesos", "Index", "Proceso")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["controller"].ToString() == "Maquina" ? "active" : "")">
                                @Html.ActionLink("Máquinas", "Index", "Maquina")
                            </li>
                        </ul>
                    </li>
                }
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reportes <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="@(ViewContext.RouteData.Values["action"].ToString() == "HorasExtraPlantaAcumulada" ? "active" : "")">
                            @Html.ActionLink("Reporte Horas Extra Planta Acumuladas Año", "HorasExtraPlantaAcumulada", "Reporte")
                        </li>
                        <li class="@(ViewContext.RouteData.Values["action"].ToString() == "HorasExtraMes" ? "active" : "")">
                            @Html.ActionLink("Reporte Horas Extra Mes", "HorasExtraMes", "Reporte")
                        </li>
                        <li class="@(ViewContext.RouteData.Values["action"].ToString() == "HorasHombrePlantaSacos" ? "active" : "")">
                            @Html.ActionLink("Horas Hombre Planta Sacos", "HorasHombrePlantaSacos", "Reporte")
                        </li>
                        <li class="@(ViewContext.RouteData.Values["action"].ToString() == "General" ? "active" : "")">
                            @Html.ActionLink("Reporte General", "General", "Reporte")
                        </li>
                    </ul>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>